### ISSUE TITLE
Add location-access-tests to 6.8?

### ISSUE THREAD

**Issue by myfirstnameispaul** [mpfr/httpd-plus#2]
I am currently running 6.8 and usually prefer to steer clear of -current as I tend not to properly keep up with changes, but I _really_ would like to make use of the `location-access-tests` to support pretty permalinks sooner than next month.

Is there a way for me to add `location-access-tests` back into httpd-plus?

**Comment by mpfr** [comment]
`location-access-tests` become available for 6.8 as soon as you install the [httpd-plus 6.8-stable branch](https://github.com/mpfr/httpd-plus/tree/6.8-stable). The moment it was imported into `-current` I was also backporting it for 6.8 and 6.7. You can find it in `updates`. Is that answering your question?
