### ISSUE TITLE
Applying patches individually

### ISSUE THREAD

**Issue by dfiguera** [mpfr/httpd-plus#3]
Is it possible/safe to apply the patches selectively?

I'm interested in the client-address-filters one but not the others.

**Comment by mpfr** [comment]
The patches must be applied one at a time in the order specified, just as implemented in the `install` script. Manually applying a single patch is not guaranteed to work.

If you're only interested in a single patch, just apply them all and ignore what you don't need. This also avoids additional work when updating.

**Comment by dfiguera** [comment]
Thank you.
